### ISSUE TITLE
Trying to pip install reggae

### ISSUE THREAD

**Issue by grd349** [darthoctopus/reggae#3]
If I pip install -e . the package, I get the following error ... 

`ERROR: Could not find a version that satisfies the requirement zeta (from reggae) (from versions: 0.7b1-py2.6.egg)
ERROR: No matching distribution found for zeta`

I see the zeta package in the requirements.  I am not familiar with the zeta package.

**Comment by darthoctopus** [comment]
The `zeta` package lives at `https://gitlab.com/darthoctopus/zeta` and is not yet available on pip. It implements analytic expressions for the zeta function and stretched echelle diagrams from Ong & Gehan (in review). I recommend you install it in develop mode for now.

**Comment by grd349** [comment]
@nielsenmb @EHatt 

Do you have this working?

**Comment by nielsenmb** [comment]
I haven't had a look at it yet. I will after new year.

**Comment by darthoctopus** [comment]
update for recordkeeping: Martin and Emily have gotten this working. Except for some packaging issues with a pure wayland ubuntu setup not installing some X11 libraries that PyQT6 expects to have around, everything worked out of the box, with `zeta` installed in develop mode.
